import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { StoreProvider } from '@/store/provider'
import { ThemeProvider } from 'next-themes'
import Navbar from '@/components/navbar/Navbar'
import { Toaster } from '@/components/ui/toaster'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={cn(
            'bg-background font-sans antialiased',
            fontSans.variable,
          )}
        >
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <Navbar />
            <div className='w-full mt-20 px-10 pt-4 pb-20'>{children}</div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  )
}
